import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
          
      </p>
      <ul>
        <li>
          <Link to="/">Stage1Web</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
